import type { Metadata } from "next";
import "../../app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import  Header from "@/components/header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className="antialiased"
      >
         <SidebarProvider>
          <AppSidebar/>
          <SidebarInset>
          <Header/>
          <div className="flex flex-col">{children}</div>
                    </SidebarInset>
         </SidebarProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
