/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  color?: "blue" | "green" | "red" | "yellow" | "purple" | "orange" | "pink" | "gray";
  createdAt?: string;
};

export type Favorite = {
  _id: string;
  _type: "favorite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teacher";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  };
  savedAt?: string;
  isActive?: boolean;
};

export type EmbeddedComment = {
  _type: "embeddedComment";
  content?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teacher";
  };
  authorId?: string;
  authorUsername?: string;
  authorRole?: "user" | "teacher";
  parentCommentId?: string;
  replies?: Array<{
    _key: string;
  } & EmbeddedComment>;
  likes?: number;
  likedBy?: Array<string>;
  createdAt?: string;
  updatedAt?: string;
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teacher";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "communityQuestion";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  };
  postType?: "community" | "blog";
  parentComment?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "comment";
  };
  replies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "comment";
  }>;
  likes?: number;
  likedBy?: Array<string>;
  createdAt?: string;
  updatedAt?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalTitle?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teacher";
  };
  communityQuestion?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "communityQuestion";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  isReported?: boolean;
  isDeleted?: boolean;
  publishedAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  username?: string;
  email?: string;
  imageURL?: string;
  role?: "member" | "moderator" | "admin" | "teacher";
  joinedAt?: string;
  blog?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  };
  communityQuestion?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "communityQuestion";
  };
  isReported?: boolean;
};

export type CommunityQuestion = {
  _id: string;
  _type: "communityQuestion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teacher";
  };
  createdAt?: string;
  comments?: Array<{
    _key: string;
  } & EmbeddedComment>;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "teacher";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  createdAt?: string;
  comments?: Array<{
    _key: string;
  } & EmbeddedComment>;
};

export type Teacher = {
  _id: string;
  _type: "teacher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  username?: string;
  email?: string;
  imageURL?: string;
  role?: "teacher" | "senior_teacher" | "lead_teacher";
  specializations?: Array<string>;
  joinedAt?: string;
  isReported?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Tag | Favorite | EmbeddedComment | Comment | Post | User | CommunityQuestion | Blog | Teacher | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(app)/blogs/[slug]/page.tsx
// Variable: query
// Query: *[_type == "blog" && slug.current == $slug][0] {      _id,      title,      description,      slug,      content,      image,      author->{        _id,        username,        imageURL,        role      },      createdAt,      _createdAt    }
export type QueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  slug: Slug | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    _id: string;
    username: string | null;
    imageURL: string | null;
    role: "admin" | "member" | "moderator" | "teacher" | null;
  } | {
    _id: string;
    username: string | null;
    imageURL: string | null;
    role: "lead_teacher" | "senior_teacher" | "teacher" | null;
  } | null;
  createdAt: string | null;
  _createdAt: string;
} | null;

// Source: ./sanity/lib/blogs/createBlog.ts
// Variable: checkExistingQuery
// Query: *[_type == "blog" && title == $title][0]            {                _id,            }
export type CheckExistingQueryResult = {
  _id: string;
} | null;
// Variable: checkSlugQuery
// Query: *[_type == "blog" && slug.current == $slug][0]                {                    _id,                }
export type CheckSlugQueryResult = {
  _id: string;
} | null;

// Source: ./sanity/lib/blogs/getBlogs.ts
// Variable: getBlogsQuery
// Query: *[_type == "blog"] {        ...,        title,        "slug": slug.current,        "author": author->,    }  | order(createdAt desc)
export type GetBlogsQueryResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: string | null;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  author: {
    _id: string;
    _type: "teacher";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    id?: string;
    username?: string;
    email?: string;
    imageURL?: string;
    role?: "lead_teacher" | "senior_teacher" | "teacher";
    specializations?: Array<string>;
    joinedAt?: string;
    isReported?: boolean;
  } | {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    id?: string;
    username?: string;
    email?: string;
    imageURL?: string;
    role?: "admin" | "member" | "moderator" | "teacher";
    joinedAt?: string;
    blog?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "blog";
    };
    communityQuestion?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "communityQuestion";
    };
    isReported?: boolean;
  } | null;
  createdAt?: string;
  comments?: Array<{
    _key: string;
  } & EmbeddedComment>;
}>;

// Source: ./sanity/lib/communties/getCommunities.ts
// Variable: getCommunitiesQuery
// Query: *[_type == "communityQuestion"] {        ...,        title,        "slug": slug.current,        "moderator": moderator->,    }  | order(createdAt desc)
export type GetCommunitiesQueryResult = Array<{
  _id: string;
  _type: "communityQuestion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  description?: string;
  slug: string | null;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  moderator: {
    _id: string;
    _type: "teacher";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    id?: string;
    username?: string;
    email?: string;
    imageURL?: string;
    role?: "lead_teacher" | "senior_teacher" | "teacher";
    specializations?: Array<string>;
    joinedAt?: string;
    isReported?: boolean;
  } | {
    _id: string;
    _type: "user";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    id?: string;
    username?: string;
    email?: string;
    imageURL?: string;
    role?: "admin" | "member" | "moderator" | "teacher";
    joinedAt?: string;
    blog?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "blog";
    };
    communityQuestion?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "communityQuestion";
    };
    isReported?: boolean;
  } | null;
  createdAt?: string;
  comments?: Array<{
    _key: string;
  } & EmbeddedComment>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"blog\" && slug.current == $slug][0] {\n      _id,\n      title,\n      description,\n      slug,\n      content,\n      image,\n      author->{\n        _id,\n        username,\n        imageURL,\n        role\n      },\n      createdAt,\n      _createdAt\n    }\n  ": QueryResult;
    "*[_type == \"blog\" && title == $title][0]\n            {\n                _id,\n            }\n        ": CheckExistingQueryResult;
    "*[_type == \"blog\" && slug.current == $slug][0]\n                {\n                    _id,\n                }\n            ": CheckSlugQueryResult;
    "*[_type == \"blog\"] {\n        ...,\n        title,\n        \"slug\": slug.current,\n        \"author\": author->,\n    }  | order(createdAt desc)": GetBlogsQueryResult;
    "*[_type == \"communityQuestion\"] {\n        ...,\n        title,\n        \"slug\": slug.current,\n        \"moderator\": moderator->,\n    }  | order(createdAt desc)": GetCommunitiesQueryResult;
  }
}
